### ISSUE TITLE
Compatibility with PHPUnit 11+

### ISSUE THREAD

**Issue by touhidurabir** [pkp/pkp-github-actions#60]
The current php unit command `PHPUNIT='php lib/pkp/lib/vendor/phpunit/phpunit/phpunit --configuration lib/pkp/tests/phpunit.xml --testdox --no-interaction'` is not compatible with latest version of PHPUnit 11 as the option `--on-interaction` has been removed from `Test Execution Options` . 

As the part of work https://github.com/pkp/pkp-lib/issues/9892 , we can and probably should upgrade the PHPUnit to version 11 which is failing to run the unit tests because of option `--on-interaction` with following error
```
PHPUnit 11.2.7 by Sebastian Bergmann and contributors.

Unknown option "--no-interaction"
```

**PRs**
https://github.com/pkp/pkp-github-actions/pull/61 [MERGED]
https://github.com/pkp/pkp-github-actions/pull/64

**Comment by touhidurabir** [comment]
@withanage can you please take a look at the linked PR at https://github.com/pkp/pkp-github-actions/issues/60#issue-2415576813 .

**Comment by withanage** [comment]
@touhidurabir  sorry, for the delay!  I reviewed the https://github.com/pkp/pkp-github-actions/pull/61 and approved it.

**Comment by touhidurabir** [comment]
@withanage can you take a look at the PR https://github.com/pkp/pkp-github-actions/pull/64 . I missed the use of `-v` flag with phpunit command which also removed for `PHPUnit 11` .

**Comment by asmecher** [comment]
This can be closed now, right, @touhidurabir?

**Comment by touhidurabir** [comment]
It should be but lets keep it open until we merged the https://github.com/pkp/pkp-lib/issues/9892

**Comment by touhidurabir** [comment]
closing this as the issue https://github.com/pkp/pkp-lib/issues/9892 got merged
